#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Cache_Money_2.Resource", IsApplication=true)]

namespace Cache_Money_2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int categories_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int frequency_array = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060018
			public const int ExpenseAdd = 2131099672;
			
			// aapt resource value: 0x7f060023
			public const int balanceText = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int button2 = 2131099681;
			
			// aapt resource value: 0x7f06000b
			public const int catSpin = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int categorySpinner = 2131099650;
			
			// aapt resource value: 0x7f06002b
			public const int checkBox1 = 2131099691;
			
			// aapt resource value: 0x7f060022
			public const int currentBalance = 2131099682;
			
			// aapt resource value: 0x7f06001d
			public const int editText1 = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int editText2 = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int editText3 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int editText4 = 2131099676;
			
			// aapt resource value: 0x7f060027
			public const int expendituresButton = 2131099687;
			
			// aapt resource value: 0x7f060005
			public const int expenseAmount = 2131099653;
			
			// aapt resource value: 0x7f060025
			public const int expenseButton = 2131099685;
			
			// aapt resource value: 0x7f06000a
			public const int expenseCancel = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int expenseSave = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int freqCheckBox = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int freqCheckBoxInc = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int freqSpin = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int frequencySpinner = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int header = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int income = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int incomeAdd = 2131099671;
			
			// aapt resource value: 0x7f06000c
			public const int incomeAmount = 2131099660;
			
			// aapt resource value: 0x7f060026
			public const int incomeButton = 2131099686;
			
			// aapt resource value: 0x7f060010
			public const int incomeCancel = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int incomeSave = 2131099663;
			
			// aapt resource value: 0x7f060024
			public const int incomeText = 2131099684;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout0 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f060028
			public const int listView1 = 2131099688;
			
			// aapt resource value: 0x7f060014
			public const int loginButton = 2131099668;
			
			// aapt resource value: 0x7f060029
			public const int name = 2131099689;
			
			// aapt resource value: 0x7f060015
			public const int newCheckBox = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int passwordBox = 2131099667;
			
			// aapt resource value: 0x7f060020
			public const int saveButton = 2131099680;
			
			// aapt resource value: 0x7f06001a
			public const int texpense = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int textView3 = 2131099666;
			
			// aapt resource value: 0x7f06001e
			public const int textView4 = 2131099678;
			
			// aapt resource value: 0x7f06002a
			public const int userName = 2131099690;
			
			// aapt resource value: 0x7f060011
			public const int usernameBox = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddExpense = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddIncome = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main0 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Overview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Register = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RegisterUser = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int ExpendituresView = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int addExpenseActivity = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int addIncomeActivity = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int category_prompt = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int frequency_prompt = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int overviewActivity = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
